"""genius loyalty levels

Revision ID: 7e74f0ff342f
Revises: 2dd65d648831
Create Date: 2026-09-02 19:19:43.643024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e74f0ff342f'
down_revision: Union[str, None] = '2dd65d648831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genius_levels',
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('stays_required', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='genius_levels_discount_check'),
    sa.CheckConstraint('stays_required >= 0', name='genius_levels_stays_check'),
    sa.CheckConstraint('tier >= 1', name='genius_levels_tier_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('tier')
    )
    op.create_table('genius_level_benefits',
    sa.Column('level_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['genius_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genius_level_benefits_level_id'), 'genius_level_benefits', ['level_id'], unique=False)
    # ### end Alembic commands ###

    _seed_default_levels()


_DEFAULT_LEVELS = [
    {
        "tier": 1,
        "slug": "level-1",
        "name": "Level 1",
        "stays_required": 2,
        "discount_percent": "10",
        "description": "Unlocked after 2 completed stays. Member-only prices on selected properties.",
        "benefits": [
            ("10% off selected stays", "Discount applied automatically at checkout.", "BedDouble"),
            ("Member-only prices", "See Genius prices flagged across the site.", "Tag"),
            ("Free cancellation on most rooms", "Flexible rates on the majority of stays.", "CalendarCheck"),
        ],
    },
    {
        "tier": 2,
        "slug": "level-2",
        "name": "Level 2",
        "stays_required": 5,
        "discount_percent": "15",
        "description": "Unlocked after 5 completed stays. Everything in Level 1, plus more.",
        "benefits": [
            ("15% off selected stays", "A bigger automatic discount on eligible stays.", "TrendingUp"),
            ("Free breakfast at 4,200+ stays", "Complimentary breakfast at participating properties.", "Coffee"),
            ("Priority email support", "Faster responses from the support team.", "Headset"),
            ("Everything in Level 1", "All Level 1 benefits carry over.", "Check"),
        ],
    },
    {
        "tier": 3,
        "slug": "level-3",
        "name": "Level 3",
        "stays_required": 10,
        "discount_percent": "20",
        "description": "Unlocked after 10 completed stays. Our highest permanent tier.",
        "benefits": [
            ("20% off selected stays", "The largest automatic Genius discount.", "TrendingUp"),
            ("Free room upgrades", "Complimentary upgrades when available.", "ArrowUpCircle"),
            ("24/7 concierge line", "Round-the-clock phone support.", "Headset"),
            ("Late checkout to 15:00", "Guaranteed late checkout at participating stays.", "Clock"),
            ("Everything in Level 2", "All Level 2 benefits carry over.", "Check"),
        ],
    },
]


def _seed_default_levels() -> None:
    levels = sa.table(
        "genius_levels",
        sa.column("id", sa.Uuid()),
        sa.column("tier", sa.SmallInteger()),
        sa.column("slug", sa.String()),
        sa.column("name", sa.String()),
        sa.column("stays_required", sa.Integer()),
        sa.column("discount_percent", sa.Numeric()),
        sa.column("description", sa.Text()),
    )
    benefits = sa.table(
        "genius_level_benefits",
        sa.column("level_id", sa.Uuid()),
        sa.column("label", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("icon", sa.String()),
        sa.column("sort_order", sa.Integer()),
    )
    bind = op.get_bind()
    for level in _DEFAULT_LEVELS:
        row = bind.execute(
            levels.insert()
            .values(
                tier=level["tier"],
                slug=level["slug"],
                name=level["name"],
                stays_required=level["stays_required"],
                discount_percent=level["discount_percent"],
                description=level["description"],
            )
            .returning(levels.c.id)
        ).first()
        level_id = row[0]
        bind.execute(
            benefits.insert(),
            [
                {
                    "level_id": level_id,
                    "label": label,
                    "description": desc,
                    "icon": icon,
                    "sort_order": index,
                }
                for index, (label, desc, icon) in enumerate(level["benefits"])
            ],
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genius_level_benefits_level_id'), table_name='genius_level_benefits')
    op.drop_table('genius_level_benefits')
    op.drop_table('genius_levels')
    # ### end Alembic commands ###
