"""guest arrival time and special requests

Revision ID: abbec2d968ef
Revises: a64a751f8c7e
Create Date: 2026-09-02 16:28:41.867436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbec2d968ef'
down_revision: Union[str, None] = 'a64a751f8c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_for', sa.String(length=20), server_default='main_guest', nullable=False))
    op.add_column('bookings', sa.Column('arrival_time', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('special_requests', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'special_requests')
    op.drop_column('bookings', 'arrival_time')
    op.drop_column('bookings', 'booking_for')
    # ### end Alembic commands ###
