"""initial schema

Revision ID: d000f529b124
Revises: 
Create Date: 2026-08-17 13:56:48.217784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd000f529b124'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), server_default=sa.text("'navy'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cms_blocks',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('block_type', sa.Text(), server_default=sa.text("'text'"), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cms_content_revisions',
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), server_default=sa.text("'Royal Vacation Admin'"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_media_folders',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_menus',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cms_pages',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('featured_image_url', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('is_homepage', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('meta_title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('author_name', sa.Text(), server_default=sa.text("'Royal Vacation Admin'"), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('page_type', sa.Text(), server_default=sa.text("'content'"), nullable=False),
    sa.Column('route_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('countries',
    sa.Column('code', sa.CHAR(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dial_code', sa.String(length=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payment_gateways',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'test'"), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('currencies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('success_url', sa.Text(), nullable=True),
    sa.Column('cancel_url', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'test', 'inactive')", name='payment_gateways_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('uq_payment_gateways_default', 'payment_gateways', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("action IN ('view','create','edit','delete')", name='permissions_action_check'),
    sa.CheckConstraint("resource IN ('dashboard','properties','bookings','guests','modules','cms','blog','reports','payments','settings','roles')", name='permissions_resource_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_permissions_resource_action', 'permissions', ['resource', 'action'], unique=False)
    op.create_table('property_types',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('count_label', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='roles_status_check'),
    sa.CheckConstraint('level >= 0', name='roles_level_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_theme',
    sa.Column('header_variant', sa.String(length=20), server_default=sa.text("'default'"), nullable=False),
    sa.Column('footer_variant', sa.String(length=20), server_default=sa.text("'classic'"), nullable=False),
    sa.Column('heading_font_size', sa.String(length=10), server_default=sa.text("'md'"), nullable=False),
    sa.Column('paragraph_font_size', sa.String(length=10), server_default=sa.text("'md'"), nullable=False),
    sa.Column('font_family', sa.String(length=30), server_default=sa.text("'outfit'"), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("font_family IN ('outfit', 'inter', 'poppins', 'playfair_display', 'roboto')", name='site_theme_font_family_check'),
    sa.CheckConstraint("footer_variant IN ('classic', 'variant_2', 'variant_3', 'variant_4', 'variant_5')", name='site_theme_footer_variant_check'),
    sa.CheckConstraint("header_variant IN ('default', 'classic', 'variant_2', 'variant_3', 'variant_4', 'variant_5')", name='site_theme_header_variant_check'),
    sa.CheckConstraint("heading_font_size IN ('sm', 'md', 'lg', 'xl')", name='site_theme_heading_font_size_check'),
    sa.CheckConstraint("paragraph_font_size IN ('sm', 'md', 'lg', 'xl')", name='site_theme_paragraph_font_size_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stay_settings',
    sa.Column('setting_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("setting_type IN ('stay_amenity', 'room_type', 'room_amenity', 'accommodation', 'board')", name='stay_settings_type_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_party_modules',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'inactive'"), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('environment', sa.String(length=20), server_default=sa.text("'development'"), nullable=False),
    sa.Column('markup_b2b_type', sa.String(length=20), server_default=sa.text("'percentage'"), nullable=False),
    sa.Column('markup_b2b_value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('markup_b2c_type', sa.String(length=20), server_default=sa.text("'percentage'"), nullable=False),
    sa.Column('markup_b2c_value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('base_currency', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('tax_type', sa.String(length=20), server_default=sa.text("'percentage'"), nullable=False),
    sa.Column('tax_value', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('credential_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment IN ('development', 'staging', 'production')", name='third_party_modules_environment_check'),
    sa.CheckConstraint("markup_b2b_type IN ('percentage', 'flat')", name='third_party_modules_markup_b2b_type_check'),
    sa.CheckConstraint("markup_b2c_type IN ('percentage', 'flat')", name='third_party_modules_markup_b2c_type_check'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='third_party_modules_status_check'),
    sa.CheckConstraint("tax_type IN ('percentage', 'flat')", name='third_party_modules_tax_type_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('blog_posts',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('author_name', sa.Text(), server_default=sa.text("'Royal Vacation Admin'"), nullable=False),
    sa.Column('meta_title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('focus_keyword', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('cms_media_assets',
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('uploaded_by', sa.Text(), server_default=sa.text("'Royal Vacation Admin'"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['cms_media_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_menu_items',
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['cms_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['cms_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_page_translations',
    sa.Column('cms_page_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('excerpt', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('meta_title', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('meta_description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cms_page_id'], ['cms_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_translation_tasks',
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_language_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'requested'"), nullable=False),
    sa.Column('requested_by', sa.Text(), server_default=sa.text("'Royal Vacation Admin'"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('cms_page','blog_post')", name='cms_translation_tasks_entity_type_check'),
    sa.CheckConstraint("status IN ('requested','done','cancelled')", name='cms_translation_tasks_status_check'),
    sa.ForeignKeyConstraint(['target_language_code'], ['languages.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cms_translation_tasks_entity', 'cms_translation_tasks', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_cms_translation_tasks_status', 'cms_translation_tasks', ['status'], unique=False)
    op.create_index('uq_cms_translation_tasks_active', 'cms_translation_tasks', ['entity_type', 'entity_id', 'target_language_code'], unique=True, postgresql_where=sa.text("status = 'requested'"))
    op.create_table('currencies',
    sa.Column('code', sa.CHAR(length=3), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate_to_aed', sa.Numeric(precision=14, scale=6), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('country_code', sa.CHAR(length=2), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate_to_aed > 0', name='currencies_rate_check'),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('uq_currencies_default', 'currencies', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("action IN ('view','create','edit','delete')", name='role_permissions_action_check'),
    sa.CheckConstraint("module IN ('dashboard','properties','bookings','guests','modules','cms','blog','reports','payments','settings','roles')", name='role_permissions_module_check'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module', 'action', name='role_permissions_unique')
    )
    op.create_index('idx_role_permissions_module', 'role_permissions', ['module'], unique=False)
    op.create_index('idx_role_permissions_role', 'role_permissions', ['role_id'], unique=False)
    op.create_table('stay_setting_translations',
    sa.Column('stay_setting_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stay_setting_id'], ['stay_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stay_setting_id', 'language_code', name='stay_setting_translations_unique')
    )
    op.create_table('blog_comments',
    sa.Column('blog_post_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('author_name', sa.Text(), nullable=False),
    sa.Column('author_email', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('is_admin_reply', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['blog_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post_translations',
    sa.Column('blog_post_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('content', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_media_asset_translations',
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('alt_text', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['cms_media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=20), server_default=sa.text("'traveler'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ip_address', postgresql.INET(), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), server_default=sa.text("'AED'"), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'Asia/Dubai'"), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('traveler', 'partner', 'admin')", name='users_account_type_check'),
    sa.CheckConstraint("gender IN ('male', 'female', 'prefer_not_to_say')", name='users_gender_check'),
    sa.CheckConstraint("status IN ('pending', 'active', 'invited', 'inactive', 'suspended', 'deleted')", name='users_status_check'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preferred_currency'], ['currencies.code'], name='users_currency_fk'),
    sa.ForeignKeyConstraint(['preferred_language'], ['languages.code'], name='users_language_fk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_account_type_status', 'users', ['account_type', 'status'], unique=False)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_table('partner_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_registration_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('business_license_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('business_phone', sa.String(length=50), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('business_city', sa.String(length=100), nullable=True),
    sa.Column('business_country', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verification_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('10.00'), nullable=False),
    sa.Column('payment_terms', sa.String(length=20), server_default=sa.text("'monthly'"), nullable=False),
    sa.Column('auto_confirm_bookings', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('max_cancellation_days', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_terms IN ('weekly', 'biweekly', 'monthly')", name='partner_profiles_payment_terms_check'),
    sa.CheckConstraint("status IN ('pending', 'active', 'suspended', 'terminated', 'rejected')", name='partner_profiles_status_check'),
    sa.CheckConstraint('commission_rate >= 0 AND commission_rate <= 100', name='partner_profiles_commission_check'),
    sa.CheckConstraint('max_cancellation_days >= 0', name='partner_profiles_max_cancellation_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_registration_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_partner_profiles_status', 'partner_profiles', ['status'], unique=False)
    op.create_table('traveler_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('loyalty_tier', sa.String(length=20), server_default=sa.text("'bronze'"), nullable=False),
    sa.Column('total_bookings', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('preferred_room_type', sa.String(length=50), nullable=True),
    sa.Column('preferred_meal_plan', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('passport_expiry', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('preferred_airlines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_hotels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('newsletter_subscribed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('marketing_consent_given', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('marketing_consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("loyalty_tier IN ('bronze', 'silver', 'gold', 'platinum')", name='traveler_profiles_loyalty_tier_check'),
    sa.CheckConstraint('NOT marketing_consent_given OR marketing_consent_given_at IS NOT NULL', name='traveler_profiles_consent_check'),
    sa.CheckConstraint('loyalty_points >= 0', name='traveler_profiles_loyalty_points_check'),
    sa.CheckConstraint('total_bookings >= 0', name='traveler_profiles_total_bookings_check'),
    sa.CheckConstraint('total_spent >= 0', name='traveler_profiles_total_spent_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_traveler_profiles_tier', 'traveler_profiles', ['loyalty_tier'], unique=False)
    op.create_table('user_login_history',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('login_type', sa.String(length=20), server_default=sa.text("'email'"), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("login_type IN ('email', 'google', 'apple', 'facebook', 'phone', 'token')", name='user_login_history_type_check'),
    sa.CheckConstraint("status IN ('success', 'failed', 'locked')", name='user_login_history_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_history_created', 'user_login_history', ['created_at'], unique=False)
    op.create_index('idx_login_history_email_failed', 'user_login_history', ['email'], unique=False, postgresql_where=sa.text("status IN ('failed', 'locked')"))
    op.create_index('idx_login_history_user', 'user_login_history', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > assigned_at', name='user_roles_expires_check'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_roles_user', 'user_roles', ['user_id'], unique=False)
    op.create_index('uq_user_roles_active', 'user_roles', ['user_id', 'role_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=20), server_default=sa.text("'desktop'"), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("device_type IN ('desktop', 'mobile', 'tablet', 'other')", name='user_sessions_device_type_check'),
    sa.CheckConstraint('expires_at > created_at', name='user_sessions_expires_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('idx_user_sessions_active', 'user_sessions', ['user_id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index('idx_user_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_activity_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_created', 'user_activity_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_resource', 'user_activity_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_activity_user', 'user_activity_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_user', table_name='user_activity_logs')
    op.drop_index('idx_activity_resource', table_name='user_activity_logs')
    op.drop_index('idx_activity_created', table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index('idx_user_sessions_user', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires', table_name='user_sessions')
    op.drop_index('idx_user_sessions_active', table_name='user_sessions', postgresql_where=sa.text('is_active'))
    op.drop_table('user_sessions')
    op.drop_index('uq_user_roles_active', table_name='user_roles', postgresql_where=sa.text('is_active'))
    op.drop_index('idx_user_roles_user', table_name='user_roles')
    op.drop_index('idx_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_login_history_user', table_name='user_login_history')
    op.drop_index('idx_login_history_email_failed', table_name='user_login_history', postgresql_where=sa.text("status IN ('failed', 'locked')"))
    op.drop_index('idx_login_history_created', table_name='user_login_history')
    op.drop_table('user_login_history')
    op.drop_index('idx_traveler_profiles_tier', table_name='traveler_profiles')
    op.drop_table('traveler_profiles')
    op.drop_index('idx_partner_profiles_status', table_name='partner_profiles')
    op.drop_table('partner_profiles')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_account_type_status', table_name='users')
    op.drop_table('users')
    op.drop_table('cms_media_asset_translations')
    op.drop_table('blog_post_translations')
    op.drop_table('blog_comments')
    op.drop_table('stay_setting_translations')
    op.drop_index('idx_role_permissions_role', table_name='role_permissions')
    op.drop_index('idx_role_permissions_module', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('uq_currencies_default', table_name='currencies', postgresql_where=sa.text('is_default'))
    op.drop_table('currencies')
    op.drop_index('uq_cms_translation_tasks_active', table_name='cms_translation_tasks', postgresql_where=sa.text("status = 'requested'"))
    op.drop_index('idx_cms_translation_tasks_status', table_name='cms_translation_tasks')
    op.drop_index('idx_cms_translation_tasks_entity', table_name='cms_translation_tasks')
    op.drop_table('cms_translation_tasks')
    op.drop_table('cms_page_translations')
    op.drop_table('cms_menu_items')
    op.drop_table('cms_media_assets')
    op.drop_table('blog_posts')
    op.drop_table('third_party_modules')
    op.drop_table('stay_settings')
    op.drop_table('site_theme')
    op.drop_table('roles')
    op.drop_table('property_types')
    op.drop_index('idx_permissions_resource_action', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('uq_payment_gateways_default', table_name='payment_gateways', postgresql_where=sa.text('is_default'))
    op.drop_table('payment_gateways')
    op.drop_table('languages')
    op.drop_table('countries')
    op.drop_table('cms_pages')
    op.drop_table('cms_menus')
    op.drop_table('cms_media_folders')
    op.drop_table('cms_content_revisions')
    op.drop_table('cms_blocks')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
