"""add contact messages

Revision ID: efb6f2e2bb2d
Revises: d000f529b124
Create Date: 2026-08-17 16:13:20.802400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb6f2e2bb2d'
down_revision: Union[str, None] = 'd000f529b124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('booking_reference', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('preferred_channel', sa.Text(), server_default=sa.text("'email'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'new'"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
