"""booking children and child ages

Revision ID: fa03fee921d6
Revises: abbec2d968ef
Create Date: 2026-09-02 16:31:52.846076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa03fee921d6'
down_revision: Union[str, None] = 'abbec2d968ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('children', sa.Integer(), server_default='0', nullable=False))
    op.add_column('bookings', sa.Column('child_ages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'child_ages')
    op.drop_column('bookings', 'children')
    # ### end Alembic commands ###
